service: aws-python-http-api-project2
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  hola-karol:
    handler: handler.hello
    events:
      - http:
          path: /hola-karol
          method: GET
